# Maintainer: Pepijn Bakker (peppidesu)
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=xorciph-bin
pkgver=0.2.0
pkgrel=1
pkgdesc="XOR cipher CLI written in Rust."
url="https://github.com/peppidesu/xorciph"
license=("APACHE")
arch=("x86_64")
provides=("xorciph")
conflicts=("xorciph")
source=("https://github.com/peppidesu/xorciph/releases/download/v$pkgver/xorciph-$pkgver-x86_64.tar.gz")
sha256sums=("9f1f69c6a94432a425a901a0a9b16400de73fc4083f4e7de430d5082dec6dc8d")

package() {
    install -Dm755 xorciph -t "$pkgdir/usr/bin"
}
