# Maintainer: Pepijn Bakker (peppidesu)
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=xorciph-bin
pkgver=0.2.2
pkgrel=1
pkgdesc="XOR cipher CLI written in Rust."
url="https://github.com/peppidesu/xorciph"
license=("APACHE")
arch=("x86_64")
provides=("xorciph")
conflicts=("xorciph")
source=("https://github.com/peppidesu/xorciph/releases/download/v$pkgver/xorciph-$pkgver-x86_64.tar.gz")
sha256sums=("0c6fd8478bb962600b390432b62a0042f939b57089ee661e0e07573bece30c34")

package() {
    install -Dm755 xorciph -t "$pkgdir/usr/bin"
}
