# Maintainer: Pepijn Bakker (peppidesu)
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=xorciph-bin
pkgver=0.3.1
pkgrel=1
pkgdesc="XOR cipher CLI written in Rust."
url="https://github.com/peppidesu/xorciph"
license=("APACHE")
arch=("x86_64")
provides=("xorciph")
conflicts=("xorciph")
source=("https://github.com/peppidesu/xorciph/releases/download/v$pkgver/xorciph-$pkgver-x86_64.tar.gz")
sha256sums=("95dee43efe49393e497c77bc307c27dcb765fd931fe07d8c5f2f50bda6754a0f")

package() {
    install -Dm755 xorciph -t "$pkgdir/usr/bin"
}
